sudo: required
services:
    - docker

before_install:
    - docker build -t afaizan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true afaizan/react-test npm test    

after_success:
    - docker build -t afaizan/multi-client ./client
    - docker build -t afaizan/multi-nginx ./nginx
    - docker build -t afaizan/multi-server ./server
    - docker build -t afaizan/multi-worker ./worker
    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin    
    # Take the images and push to docker hub
    - docker push afaizan/multi-client
    - docker push afaizan/multi-nginx
    - docker push afaizan/multi-server
    - docker push afaizan/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucker_name: elasticbeanstalk-us-east-2-179339261954
    bucker_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY        

    

